import {describe,expect,it} from 'vitest';
import {validateV10State} from '../src/duel/v10-storage.js';
import {CARDS} from '../src/duel/cards.js';
import {createV10Duel,enterV10Node} from '../src/duel/engine.js';

// Regression: the V10 save validator only checked `typeof c.kind === 'string'`, so a save
// carrying a card kind that is not in CARDS passed validation. The deck modal then read
// CARDS[kind].type and threw, landing on ErrorBoundary with no recovery path. Before this,
// `validateV10State` returned TRUE for the counterexample below.

function validBattleSave(){
  const base=createV10Duel(20260910);
  return enterV10Node(base,base.runMap.nodes.find(n=>n.type==='battle').id);
}

describe('V10 save validation rejects card kinds that are not in CARDS',()=>{
  it('rejects a deck whose card kind does not exist in CARDS',()=>{
    const s=validBattleSave();
    expect(validateV10State(s)).toBe(true);
    s.deck[0]={...s.deck[0],kind:'__not_a_real_card__'};
    expect(validateV10State(s)).toBe(false);
  });

  it('rejects a counterexample save that used to slip through',()=>{
    const s=validBattleSave();
    s.deck[0]={...s.deck[0],kind:' banana '};
    s.runOuts=' banana ';
    s.nextId='not-a-number';
    s.stats='not-an-object';
    expect(validateV10State(s)).toBe(false);
  });

  it('rejects a mid-battle save that has no battle object',()=>{
    const s=validBattleSave();
    expect(s.phase).toBe('battle');
    s.battle=null;
    expect(validateV10State(s)).toBe(false);
  });

  it('rejects non-array relicChoices',()=>{
    const s=validBattleSave();
    s.v10.relicChoices={};
    expect(validateV10State(s)).toBe(false);
  });

  it('returns false (never throws) when v10 is missing or not an object',()=>{
    // Before: `s.v10.relicChoices` was read before the `!s.v10` guard,
    // so a v10-less save threw TypeError instead of a clean reject.
    for(const v10 of [undefined,null,42,'v10',[]]){
      const s=validBattleSave();
      s.v10=v10;
      expect(()=>validateV10State(s)).not.toThrow();
      expect(validateV10State(s)).toBe(false);
    }
  });

  it('still accepts a sound save that predates an optional field',()=>{
    // Optional fields (runOuts, nextId, stats) must not invalidate an otherwise
    // sound save: the engine coerces a missing runOuts via `s.runOuts|0`.
    // (This used the P0-1 fixture while it predated runOuts; the fixture has
    // since been regenerated by the intentional P1 deal change, so the case is
    // constructed directly now.)
    const s=validBattleSave();
    delete s.runOuts;delete s.nextId;delete s.stats;
    expect(validateV10State(s)).toBe(true);
  });

  it('accepts every card kind the engine can produce',()=>{
    const s=validBattleSave();
    for(const c of s.deck)expect(Object.hasOwn(CARDS,c.kind)).toBe(true);
  });
});