import fs from 'node:fs';
import path from 'node:path';

const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36';
const FONTDIR = 'public/fonts';

const sources = [
  { url: 'https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@400;500;600;700;800;900&display=swap', name: 'NotoSansKR' },
  { url: 'https://fonts.googleapis.com/css2?family=Gowun+Dodum&family=Black+Han+Sans&family=Silkscreen&display=swap', name: 'Display' },
];

fs.mkdirSync(FONTDIR, { recursive: true });

let allCss = '';
let count = 0;
const fetchOne = async (url, name) => {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  let css = await res.text();
  const urls = [...css.matchAll(/url\((https:[^)]+\.woff2)\)/g)].map(m => m[1]);
  const unique = [...new Set(urls)];
  console.log(`${name}: ${unique.length} woff2 urls`);
  for (const u of unique) {
    const file = u.split('/').slice(-2).join('/').replace(/\//g, '-');
    const dest = path.join(FONTDIR, file);
    if (!fs.existsSync(dest)) {
      const buf = Buffer.from(await (await fetch(u)).arrayBuffer());
      fs.writeFileSync(dest, buf);
      console.log(`  + ${file} ${(buf.length / 1024) | 0}KB`);
    }
    css = css.split(u).join(`/fonts/${file}`);
    count++;
  }
  return css;
};

for (const s of sources) allCss += await fetchOne(s.url, s.name) + '\n';

allCss = allCss.replace(/\}/g, '}\n');
fs.mkdirSync('src/duel', { recursive: true });
fs.writeFileSync('src/duel/fonts.css', `/* Self-hosted copies of the fonts the app used to pull from Google's CDN.\n * SIL Open Font License 1.1; see NOTICE.md. Generated by scripts/fetch-fonts.mjs. */\n` + allCss);
console.log(`wrote src/duel/fonts.css, ${count} url rewrites`);
